In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
cond = (a<3)
cond

array([ True,  True, False, False, False, False], dtype=bool)

In [4]:
a[cond]

array([1, 2])

In [5]:
a.shape

(6L,)

In [6]:
b = a.reshape((3,2))
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
a[0:3]

array([1, 2, 3])

In [8]:
a.reshape((a.shape[0],1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])