<hr/>

# Data Mining [EN.550.436]
**Tamás Budavári** - budavari@jhu.edu <br/>
**Class 21** - November 28, 2016

- Self-organizing maps
- Neural networks

<hr/>

## Self-Organizing Maps aka Kohonen Networks

- Unsupervised learning of low-dimensional representation, e.g., for visualization

> A $d$ dimensional grid is gradualy adjusted to fit the data

<img src=http://mathworld.wolfram.com/images/eps-gif/GridGraph_701.gif align=left width=230>
<img src=http://farm3.static.flickr.com/2762/4288819804_7c3e34a1cb.jpg align=center width=200>


## Algorithms

- Learning

>0. Each point is assigned to closest grid point
>0. Winning grid point is adjusted as well as its neighbors
>0. Repeat till convergence

- Mapping

>0. Find closest grid point 
>0. Or interpolation

<img src=https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Somtraining.svg/750px-Somtraining.svg.png align=left width=400>


## Animation

<a href="http://www.youtube.com/watch?v=aQkIg69ZAXs"><img src="http://img.youtube.com/vi/aQkIg69ZAXs/0.jpg" align=left width=300></a>

## Assumes shape

- E.g., 1-D grid becomes a "principal curve"

<img src=https://upload.wikimedia.org/wikipedia/commons/b/bb/SOMsPCA.PNG align=left width=230>

## Limitations

- Random initialization could get the grid entangled

> Hard to disentangle it!

- Best bet is to detect and abandon for another init

## Artificial Neural Networks

- Supervised learning of nonlinear relations

> Classic example is ```XOR``` (eXclusive OR)

- Modeled after neurons and synapses of the brain

> Connected nodes determine each others value

## Nonlinear Problem

- Exclusive OR

<img src=http://www.saedsayad.com/images/Perceptron_XOR.png align=left width=300>

## Layers

- Simplest case: input-hidden-output (also a *bias* node)

<!--
<img src=http://www.codeproject.com/KB/dotnet/predictor/network.jpg align=left width=350>
<img src=https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Colored_neural_network.svg/300px-Colored_neural_network.svg.png align=left width=200>-->

<img src=files/network.jpg align=left width=350>




## Each Neuron

- Add inputs and apply an *activation* function

> E.g., nonlinear *sigmoid* function

> Cf. posterior probability and Bayes factor

&nbsp;

<img src=http://jmvidal.cse.sc.edu/talks/ann/ann-sigmoid.png align=left width=400>

## ANN for XOR

- For example,

<img src=http://www.doc.ic.ac.uk/~nd/surprise_96/journal/vol2/cs11/article2.xor2.jpg align=left width=150>

<!--<img src=http://www.cs.vassar.edu/~weltyc/oldcourses/cogsci100.98f/img001.jpg align=left width=500>

<img src=https://www.byclb.com/TR/Tutorials/neural_networks/ch8_1_dosyalar/image072.jpg align=left width=150> -->

## Check this out

- Does this work with activation functions

> $I(x)=x$ (identity) or

> $H(x)=1$ if $x\!>\!0$ and $0$ otherwise?

<img src=https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQL-LhbCs9XCG7g0kKeiJh3fs27plP04FgmXd8OWjezvwNSU9Fzmw align=left width=200>

## Learning the Weights

- Backpropagation algorithm

> Change weights to minimize the error <br>
> knowing the function and its derivatives

## Using sklearn
http://scikit-learn.org/stable/modules/neural_networks_supervised.html

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [117]:
from sklearn.neural_network import MLPClassifier

# XOR example
X = [[0,0], [1,1], [0,1], [1,0]]
y = [0, 0, 1, 1]

clf = MLPClassifier(hidden_layer_sizes=(2,), 
                    activation='logistic', solver='lbfgs')
clf.fit(X,y)
clf.predict(X)

array([0, 0, 1, 1])

In [3]:
for layer in range(len(clf.coefs_)):
    print '-->', layer, clf.intercepts_[layer]
    print clf.coefs_[layer]
    print

--> 0 [ 4.03893429  3.39610882]
[[-6.93514317  6.33063689]
 [ 6.23865659 -6.06701591]]

--> 1 [ 21.62750533]
[[-14.29139751]
 [-14.55103646]]



## Deep Learning
- Many layers
- Special architecture

<img src="http://deeplearning.net/tutorial/_images/mylenet.png" width=600 align=left>